#!/bin/bash

tag=":latest"
if [ ! -z "${1}" ] ; then
    tag=":${1}"
fi

#Step 1: Prepare for RootFS firstly
yum install -y -q wget
if [ ! -f "./Ubuntu_ARM64.tar.gz" ] ; then
    wget ftp://117.78.41.188/pre-releases/3.0/b3/linux/Ubuntu/Ubuntu_ARM64.tar.gz
fi

if [ ! -d "./Ubuntu" ] ; then
    mkdir "./Ubuntu" 
fi
tar -zxvf Ubuntu_ARM64.tar.gz -C ./Ubuntu
sudo chroot ./Ubuntu /bin/bash -x <<'EOF'
su -
apt purge -y libffi6:arm64
apt purge -y git-man
apt purge -y rsyslog
apt purge -y libperl5
apt purge -y libxcb1:arm64
apt purge -y libxpm4:arm64
apt purge -y python3-jinja2
apt purge -y libsqlite3-0:arm64
apt purge -y libxcb1-dev:arm64
apt purge -y init
apt purge -y libxaw7:arm64
apt purge -y libnfnetlink0:arm64
apt purge -y apport
apt purge -y libpci3:arm64
apt purge -y makedev
apt purge -y libcap2:arm64
apt purge -y libasan2:arm64
apt purge -y x11proto-core-dev
apt purge -y mdadm
apt purge -y ssh-import-id
apt purge -y gfortran
apt purge -y libwind0-heimdal:arm64
apt purge -y friendly-recovery
apt purge -y libtiff5:arm64
apt purge -y libsmartcols1:arm64
apt purge -y update-manager-core
apt purge -y python3-json-pointer
apt purge -y libnetfilter-conntrack3:arm64
apt purge -y parted
apt purge -y dosfstools
apt purge -y libtext-wrapi18n-perl
apt purge -y cron
apt purge -y libisccfg140:arm64
apt purge -y libxrandr-dev:arm64
apt purge -y python2
apt purge -y plymouth-theme-ubuntu-text
apt purge -y libyaml-0-2:arm64
apt purge -y nano
apt purge -y libxrender1:arm64
apt purge -y libatm1:arm64
apt purge -y libxi6:arm64
apt purge -y libcairo2:arm64
apt purge -y policykit-1
apt purge -y lxrandr
apt purge -y install-info
apt purge -y libpam-runtime
apt purge -y libapt-inst2
apt purge -y libgomp1:arm64
apt purge -y ureadahead
apt purge -y python3-prettytable
apt purge -y python-minimal
apt purge -y dnsutils
apt purge -y manpages-dev
apt purge -y dmidecode
apt purge -y gfortran-5
apt purge -y ltrace
apt purge -y liblvm2app2
apt purge -y mlocate
apt purge -y apt
apt purge -y vim
apt purge -y ntfs-3g
apt purge -y libasprintf0v5:arm64
apt purge -y xz-utils
apt purge -y libutempter0:arm64
apt purge -y libgmp10:arm64
apt purge -y python3-jsonpatch
apt purge -y init-system-helpers
apt purge -y x11-xserver-utils
apt purge -y libmount1:arm64
apt purge -y linux-generic
apt purge -y debconf-i18n
apt purge -y python3-gi
apt purge -y bcache-tools
apt purge -y sysv-rc
apt purge -y netcat-openbsd
apt purge -y python3-idna
apt purge -y libx11-6:arm64
apt purge -y xkb-data
apt purge -y libapt-pkg5
apt purge -y libpolkit-backend-1-0:arm64
apt purge -y libthai0:arm64
apt purge -y python-cairo
apt purge -y liblvm2cmd2
apt purge -y uidmap
apt purge -y cloud-guest-utils
apt purge -y liblxc1
apt purge -y libpam-systemd:arm64
apt purge -y ubuntu-server
apt purge -y ifenslave
apt purge -y libxtables11:arm64
apt purge -y zlib1g:arm64
apt purge -y cgroupfs-mount
apt purge -y iptables
apt purge -y sudo
apt purge -y libtext-iconv-perl
apt purge -y logrotate
apt purge -y base-files
apt purge -y libxdmcp-dev:arm64
apt purge -y libxcursor1:arm64
apt purge -y libxdamage1:arm64
apt purge -y libhcrypto4-heimdal:arm64
apt purge -y libxmu6:arm64
apt purge -y libplymouth4:arm64
apt purge -y insserv
apt purge -y libpango-1
apt purge -y libdebconfclient0:arm64
apt purge -y vlan
apt purge -y gcc
apt purge -y python3-six
apt purge -y multiarch-support
apt purge -y snapd
apt purge -y libxcomposite1:arm64
apt purge -y python3-cffi-backend
apt purge -y klibc-utils
apt purge -y libpopt0:arm64
apt purge -y ncurses-term
apt purge -y libice6:arm64
apt purge -y libbsd0:arm64
apt purge -y libjpeg-turbo8:arm64
apt purge -y pciutils
apt purge -y libmagic1:arm64
apt purge -y librtmp1:arm64
apt purge -y libdbus-1-3:arm64
apt purge -y python3-markupsafe
apt purge -y lsb-base
apt purge -y acpid
apt purge -y kbd
apt purge -y fonts-dejavu-core
apt purge -y sensible-utils
apt purge -y python3-cryptography
apt purge -y whiptail
apt purge -y liblocale-gettext-perl
apt purge -y libdb5
apt purge -y console-setup
apt purge -y squashfs-tools
apt purge -y libpam-modules:arm64
apt purge -y python3-pkg-resources
apt purge -y libhogweed4:arm64
apt purge -y libgssapi3-heimdal:arm64
apt purge -y python3-debian
apt purge -y libdevmapper-event1
apt purge -y eatmydata
apt purge -y lxc-common
apt purge -y xml-core
apt purge -y dmsetup
apt purge -y python3-pyasn1
apt purge -y libkrb5support0:arm64
apt purge -y libjpeg8:arm64
apt purge -y libaccountsservice0:arm64
apt purge -y libelf1:arm64
apt purge -y libsm6:arm64
apt purge -y libx11-dev:arm64
apt purge -y xtrans-dev
apt purge -y adduser
apt purge -y ed
apt purge -y libreadline6:arm64
apt purge -y libfuse2:arm64
apt purge -y libcryptsetup4:arm64
apt purge -y patch
apt purge -y unattended-upgrades
apt purge -y ftp
apt purge -y flash-kernel
apt purge -y libhx509-5-heimdal:arm64
apt purge -y runc
apt purge -y libcomerr2:arm64
apt purge -y libxcb-render0:arm64
apt purge -y rc
apt purge -y python3-requests
apt purge -y ubuntu-standard
apt purge -y gir1
apt purge -y libk5crypto3:arm64
apt purge -y libgcc-5-dev:arm64
apt purge -y libnuma1:arm64
apt purge -y libreadline5:arm64
apt purge -y fonts-ubuntu-font-family-console
apt purge -y libheimbase1-heimdal:arm64
apt purge -y openssl
apt purge -y fontconfig-config
apt purge -y accountsservice
apt purge -y lxd
apt purge -y libgpg-error0:arm64
apt purge -y libklibc
apt purge -y cryptsetup
apt purge -y lvm2
apt purge -y gpgv
apt purge -y libthai-data
apt purge -y lshw
apt purge -y libgssapi-krb5-2:arm64
apt purge -y libcc1-0:arm64
apt purge -y libheimntlm0-heimdal:arm64
apt purge -y libc-bin
apt purge -y libattr1:arm64
apt purge -y sosreport
apt purge -y libubsan0:arm64
apt purge -y byobu
apt purge -y xdg-user-dirs
apt purge -y libharfbuzz0b:arm64
apt purge -y libp11-kit0:arm64
apt purge -y libpangocairo-1
apt purge -y libncursesw5:arm64
apt purge -y libxau6:arm64
apt purge -y groff-base
apt purge -y libpthread-stubs0-dev:arm64
apt purge -y libslang2:arm64
apt purge -y libc6-dev:arm64
apt purge -y python3-apport
apt purge -y libxrender-dev:arm64
apt purge -y hdparm
apt purge -y bsdutils
apt purge -y linux-image-4
apt purge -y libxdmcp6:arm64
apt purge -y dpkg
apt purge -y iputils-ping
apt purge -y ubuntu-cloudimage-keyring
apt purge -y libatk1
apt purge -y libsasl2-modules-db:arm64
apt purge -y liblwres141:arm64
apt purge -y libgdk-pixbuf2
apt purge -y mtr-tiny
apt purge -y gnupg
apt purge -y libbz2-1
apt purge -y hicolor-icon-theme
apt purge -y liblz4-1:arm64
apt purge -y xfsprogs
apt purge -y libeatmydata1:arm64
apt purge -y libustr-1
apt purge -y libdrm2:arm64
apt purge -y libusb-0
apt purge -y libusb-1
apt purge -y dash
apt purge -y python3-update-manager
apt purge -y openssh-sftp-server
apt purge -y libpangoft2-1
apt purge -y libxinerama1:arm64
apt purge -y x11proto-kb-dev
apt purge -y python3-dbus
apt purge -y libpixman-1-0:arm64
apt purge -y libnewt0
apt purge -y openssh-server
apt purge -y libblkid1:arm64
apt purge -y libcups2:arm64
apt purge -y ncurses-bin
apt purge -y libwrap0:arm64
apt purge -y libfribidi0:arm64
apt purge -y libgnutls-openssl27:arm64
apt purge -y krb5-locales
apt purge -y libjbig0:arm64
apt purge -y pastebinit
apt purge -y libgirepository-1
apt purge -y libdns-export162
apt purge -y vim-runtime
apt purge -y eject
apt purge -y libevent-2
apt purge -y apt-transport-https
apt purge -y python-apt-common
apt purge -y libpython-stdlib:arm64
apt purge -y ubuntu-release-upgrader-core
apt purge -y vim-tiny
apt purge -y python3-newt
apt purge -y debianutils
apt purge -y libgeoip1:arm64
apt purge -y libxext6:arm64
apt purge -y linux-libc-dev:arm64
apt purge -y grub-legacy-ec2
apt purge -y libcurl3-gnutls:arm64
apt purge -y btrfs-tools
apt purge -y libstdc++6:arm64
apt purge -y software-properties-common
apt purge -y liberror-perl
apt purge -y libgcc1:arm64
apt purge -y libtext-charwidth-perl
apt purge -y dns-root-data
apt purge -y fontconfig
apt purge -y lxd-client
apt purge -y pollinate
apt purge -y python-gobject-2
apt purge -y libssl1
apt purge -y ethtool
apt purge -y libxrandr2-dbg:arm64
apt purge -y bash-completion
apt purge -y libnih1:arm64
apt purge -y python3-apt
apt purge -y liblzo2-2:arm64
apt purge -y x11proto-input-dev
apt purge -y update-notifier-common
apt purge -y sgml-base
apt purge -y libpam-modules-bin
apt purge -y libselinux1:arm64
apt purge -y libgnutls30:arm64
apt purge -y python3-blinker
apt purge -y net-tools
apt purge -y libsepol1:arm64
apt purge -y libavahi-common-data:arm64
apt purge -y debconf
apt purge -y python3-distupgrade
apt purge -y python3-oauthlib
apt purge -y libxrandr2:arm64
apt purge -y libisc160:arm64
apt purge -y bsdmainutils
apt purge -y gcc-5
apt purge -y libpcap0
apt purge -y libpcre3:arm64
apt purge -y x11proto-randr-dev
apt purge -y x11proto-render-dev
apt purge -y isc-dhcp-common
apt purge -y ubuntu-fan
apt purge -y libncurses5:arm64
apt purge -y libldap-2
apt purge -y irqbalance
apt purge -y screen
apt purge -y libisc-export160
apt purge -y libfdisk1:arm64
apt purge -y distro-info-data
apt purge -y ubuntu-minimal
apt purge -y libaudit1:arm64
apt purge -y libidn11:arm64
apt purge -y apport-symptoms
apt purge -y libitm1:arm64
apt purge -y mime-support
apt purge -y libnettle6:arm64
apt purge -y cpp-5
apt purge -y libcap-ng0:arm64
apt purge -y login
apt purge -y lsof
apt purge -y libkrb5-3:arm64
apt purge -y libgfortran-5-dev:arm64
apt purge -y libdatrie1:arm64
apt purge -y ucf
apt purge -y linux-headers-4
apt purge -y libgcrypt20:arm64
apt purge -y cloud-initramfs-dyn-netconf
apt purge -y lsb-release
apt purge -y devio
apt purge -y containerd
apt purge -y libpng12-0:arm64
apt purge -y libxmuu1:arm64
apt purge -y libkmod2:arm64
apt purge -y netbase
apt purge -y libaudit-common
apt purge -y bridge-utils
apt purge -y mawk
apt purge -y powermgmt-base
apt purge -y telnet
apt purge -y libc6:arm64
apt purge -y locales
apt purge -y busybox-static
apt purge -y apt-utils
apt purge -y libss2:arm64
apt purge -y mount
apt purge -y language-selector-common
apt purge -y resolvconf
apt purge -y procps
apt purge -y libgdbm3:arm64
apt purge -y python3-commandnotfound
apt purge -y rename
apt purge -y libsemanage-common
apt purge -y python3-gdbm:arm64
apt purge -y initramfs-tools
apt purge -y e2fslibs:arm64
apt purge -y systemd-sysv
apt purge -y make
apt purge -y libkeyutils1:arm64
apt purge -y man-db
apt purge -y libuuid1:arm64
apt purge -y libsasl2-modules:arm64
apt purge -y libfreetype6:arm64
apt purge -y popularity-contest
apt purge -y libx11-doc
apt purge -y libxml2:arm64
apt purge -y dmeventd
apt purge -y fuse
apt purge -y manpages
apt purge -y xauth
apt purge -y libgpm2:arm64
apt purge -y libxfixes3:arm64
apt purge -y iso-codes
apt purge -y libpipeline1:arm64
apt purge -y libbind9-140:arm64
apt purge -y libexpat1:arm64
apt purge -y linux-base
apt purge -y iproute2
apt purge -y libxau-dev:arm64
apt purge -y docker
apt purge -y libmpc3:arm64
apt purge -y libavahi-common3:arm64
apt purge -y vim-common
apt purge -y less
apt purge -y x11proto-xext-dev
apt purge -y libjson-c2:arm64
apt purge -y xorg-sgml-doctools
apt purge -y libacl1:arm64
apt purge -y libapparmor1:arm64
apt purge -y python3
apt purge -y apparmor
apt purge -y libgtk2
apt purge -y lxcfs
apt purge -y libavahi-client3:arm64
apt purge -y linux-image-generic
apt purge -y initramfs-tools-core
apt purge -y libkrb5-26-heimdal:arm64
apt purge -y python3-minimal
apt purge -y run-one
apt purge -y tmux
apt purge -y iputils-tracepath
apt purge -y readline-common
apt purge -y ubuntu-core-launcher
apt purge -y libroken18-heimdal:arm64
apt purge -y bind9-host
apt purge -y gcc-6-base:arm64
apt purge -y python3-software-properties
apt purge -y busybox-initramfs
apt purge -y gettext-base
apt purge -y libisl15:arm64
apt purge -y sysvinit-utils
apt purge -y udev
apt purge -y libgfortran3:arm64
apt purge -y python3-urllib3
apt purge -y python3-systemd
apt purge -y rsync
apt purge -y openssh-client
apt purge -y psmisc
apt purge -y libedit2:arm64
apt purge -y linux-firmware
apt purge -y libmnl0:arm64
apt purge -y python3-pycurl
apt purge -y libsigsegv2:arm64
apt purge -y libprocps4:arm64
apt purge -y libsasl2-2:arm64
apt purge -y liblzma5:arm64
apt purge -y cryptsetup-bin
apt purge -y libdevmapper1
apt purge -y libfontconfig1:arm64
apt purge -y wget
apt purge -y libudev1:arm64
apt purge -y libsemanage1:arm64
apt purge -y ufw
apt purge -y strace
apt purge -y libxt6:arm64
apt purge -y libpolkit-agent-1-0:arm64
apt purge -y libpam0g:arm64
apt purge -y libicu55:arm64
apt purge -y python3-serial
apt purge -y libestr0
apt purge -y cloud-initramfs-copymods
apt purge -y libseccomp2:arm64
apt purge -y tcpd
apt purge -y libglib2
apt purge -y libisccc140:arm64
apt purge -y python3-yaml
apt purge -y overlayroot
apt purge -y gdisk
apt purge -y perl
apt purge -y git
apt purge -y libapparmor-perl
apt purge -y libasn1-8-heimdal:arm64
apt purge -y libtasn1-6:arm64
apt purge -y arandr
apt purge -y python-gtk2
apt purge -y open-iscsi
apt purge -y x11-common
apt purge -y tcpdump
apt purge -y initramfs-tools-bin
apt purge -y libcap2-bin
apt purge -y python3-chardet
apt purge -y gcc-5-base:arm64
apt purge -y libxxf86vm1:arm64
apt purge -y initscripts
apt purge -y plymouth
apt purge -y libdns162:arm64
apt purge -y libx11-data
apt purge -y python3-problem-report
apt purge -y console-setup-linux
apt purge -y ifupdown
apt purge -y isc-dhcp-client
apt purge -y python3-configobj
apt purge -y libxext-dev:arm64
apt purge -y geoip-database
apt purge -y at
apt purge -y file
apt purge -y libdbus-glib-1-2:arm64
apt purge -y bzip2
apt purge -y perl-modules-5
apt purge -y libpython2
apt purge -y libxcb-shm0:arm64
apt purge -y libpython3-stdlib:arm64
apt purge -y linux-headers-generic
apt purge -y libparted2:arm64
apt purge -y libatomic1:arm64
apt purge -y python3-jwt
apt purge -y time
apt purge -y libmpfr4:arm64
apt purge -y dnsmasq-base
apt purge -y keyboard-configuration
apt purge -y libtinfo5:arm64
apt purge -y uuid-runtime
apt purge -y libpolkit-gobject-1-0:arm64
apt purge -y ubuntu-keyring
apt purge -y libmpdec2:arm64
apt purge -y usbutils
apt purge -y e2fsprogs
apt purge -y command-not-found
apt purge -y libpython3
apt purge -y libsystemd0:arm64
apt purge -y perl-base
apt purge -y libc-dev-bin
apt purge -y command-not-found-data
apt purge -y cpp
apt purge -y libgraphite2-3:arm64
apt purge -y base-passwd
apt purge -y dh-python

apt-get -y autoremove

rm -fr /usr/local/estuary/*
rm -fr /boot/*
rm -fr /usr/lib/modules/*
rm -fr /usr/lib/firmware/*

localedef --list-archive | grep -v -i ^en | xargs localedef --delete-from-archive 
mv /usr/lib/locale/locale-archive /usr/lib/locale/locale-archive.tmpl 
build-locale-archive 
echo > /usr/lib/locale/locale-archive.tmpl

EOF

#Save latest base image
pushd ./Ubuntu > /dev/null
tar -czvf ../Ubuntu_BaseImage.tar.gz .
popd > /dev/null

#Clear unused files
rm -fr ./Ubuntu
rm -fr ./Ubuntu_ARM64.tar.gz

#Step 2: Start docker Service 
yum install -y -q docker
service docker start

#Step 3: Build docker base image
docker build -t openestuary/ubuntu${tag} .
