FROM scratch
MAINTAINER sjtuhjh@hotmail.com
ADD Ubuntu_BaseImage.tar.gz /

LABEL name="Estuary Ubuntu Base Image " \
      vendor="Estuary Ubuntu" \
      license="GPLv2" \
      build-date="20170126"

CMD ["/bin/bash"]

