FROM scratch
MAINTAINER sjtuhjh@hotmail.com
ADD CentOS_ARM64.tar.gz /


LABEL name="Estuary CentOS Base Image " \
      vendor="Estuary CentOS" \
      license="GPLv2" \
      build-date="20170104"


CMD ["/bin/bash"]

