FROM scratch
MAINTAINER sjtuhjh@hotmail.com
ADD CentOS_BaseImage.tar.gz /

LABEL name="Estuary CentOS Base Image " \
      vendor="Estuary CentOS" \
      license="GPLv2" \
      build-date="20170126"

CMD ["/bin/bash"]

